version: '3'
services:
  db:
    image: postgres:14.5
    restart: 'no'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_astra
    ports:
      - "5432:5432"
